name: dev_authentication
description: A new Flutter project.
publish_to: 'none' 

version: 1.3.7+43

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auth_package:
    path: packages/auth_package
  logger: ^1.4.0
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_modular: ^5.0.3
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  mobx_codegen: ^2.3.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    
flutter_intl:
  enabled: true
