AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Authentication Dev Frontend
Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to store the website content
  AcmCertificateArn:
    Type: String
    Description: ARN of the ACM certificate to use for the CloudFront distribution
  AlternateDomainName:
    Type: String
    Description: Alternate domain name to use for the CloudFront distribution
  HostedZoneId:
    Type: String
    Description: Hosted zone Id to use in record route 53
Resources:
  CloudFrontOriginAccessControl:
    Type: 'AWS::CloudFront::OriginAccessControl'
    Properties:
      OriginAccessControlConfig:
        Description: !Sub '${BucketName} OAC'
        Name: !Sub '${BucketName} OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref AlternateDomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021 
        Comment: !Ref BucketName 
        HttpVersion: http2
        Origins:
          - Id: !Ref MyBucket
            DomainName: !GetAtt MyBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Ref MyBucket
          ViewerProtocolPolicy : redirect-to-https
        DefaultRootObject: index.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Statement:
            Sid: 'AllowCloudFrontServicePrincipal'
            Effect: Allow
            Action: 's3:GetObject'
            Resource:
              - !Sub "arn:aws:s3:::${MyBucket}/*"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudfrontDistribution}"
  RecordRoute53:
    Type: AWS::Route53::RecordSet
    Properties: 
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        HostedZoneId: 'Z2FDTNDATAQYW2'
      Name: !Ref AlternateDomainName
      Type: 'A'
      HostedZoneId: !Ref HostedZoneId
Outputs:
  AwsBucket:
    Value: !Ref MyBucket
  CloudfrontId:
    Value: !Ref CloudfrontDistribution
